apiVersion: v1
kind: Service
metadata:
  name: live-conversation-conversation-service-service
  namespace: dev
spec:
  ports:
  - name: live-conversation-conversation-service-service
    port: 8999
    protocol: TCP
    targetPort: 8999
  selector:
    app: live-conversation-conversation-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: live-conversation-conversation-service-deployment
  name: live-conversation-conversation-service-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: live-conversation-conversation-service
  template:
    metadata:
      labels:
        app: live-conversation-conversation-service
    spec:
      containers:
      - env:
        - name: myVar2
          value: myVarValue2
        image: crdevwe001.azurecr.io/live-conversation/conversation-service:b8ce484b7d06b1f1b1be296e5e2e9aeedb582397
        name: live-conversation-conversation-service
        ports:
        - containerPort: 8999
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: live-conversation-conversation-service-ingress
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
  - host: live-dev.labmojodoo.com
    http:
      paths:
      - backend:
          service:
            name: live-conversation-conversation-service-service
            port:
              number: 8999
        path: /ws/?(.*)
        pathType: Prefix
  tls:
  - hosts:
    - live-dev.labmojodoo.com
    secretName: tls-live-dev
