apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-conversation-conversation-service-deployment
  labels:
    app.kubernetes.io/name: live-conversation-conversation-service-deployment
spec:
 selector:
    matchLabels:
      app: live-conversation-conversation-service
 template:
   spec:
     containers:
       - name: live-conversation-conversation-service
         env: 
           - name: socketUrl
             value: wss://live-dev.labmojodo.com:443/ws
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: live-conversation-conversation-service-ingress
spec: 
  tls:
    - hosts:
        - live-dev.labmojodoo.com
      secretName: tls-live-dev  

